-- Resource pool for the game. Max 12 resources (REQUIREMENTS.md §27).
local resources = {
  {
    id = "stone",
    name = "Stone",
    rarity = "common",
    unlockDepth = 1,
    basePrice = 1,
    storageBaseCapacity = 200,
    generationWeightByDepth = { { fromDepth = 1, weight = 60 } },
  },
  {
    id = "coal",
    name = "Coal",
    rarity = "common",
    unlockDepth = 1,
    basePrice = 2,
    storageBaseCapacity = 150,
    generationWeightByDepth = { { fromDepth = 1, weight = 30 } },
  },
  {
    id = "copper",
    name = "Copper",
    rarity = "uncommon",
    unlockDepth = 2,
    basePrice = 5,
    storageBaseCapacity = 100,
    generationWeightByDepth = { { fromDepth = 1, weight = 0 }, { fromDepth = 2, weight = 25 } },
  },
  {
    id = "tin",
    name = "Tin",
    rarity = "uncommon",
    unlockDepth = 2,
    basePrice = 6,
    storageBaseCapacity = 100,
    generationWeightByDepth = { { fromDepth = 2, weight = 20 } },
  },
  {
    id = "iron",
    name = "Iron",
    rarity = "uncommon",
    unlockDepth = 3,
    basePrice = 8,
    storageBaseCapacity = 100,
    generationWeightByDepth = { { fromDepth = 3, weight = 25 } },
  },
  {
    id = "zinc",
    name = "Zinc",
    rarity = "uncommon",
    unlockDepth = 3,
    basePrice = 9,
    storageBaseCapacity = 100,
    generationWeightByDepth = { { fromDepth = 3, weight = 15 } },
  },
  {
    id = "silver",
    name = "Silver",
    rarity = "rare",
    unlockDepth = 4,
    basePrice = 15,
    storageBaseCapacity = 80,
    generationWeightByDepth = { { fromDepth = 4, weight = 15 } },
  },
  {
    id = "quartz",
    name = "Quartz",
    rarity = "rare",
    unlockDepth = 4,
    basePrice = 12,
    storageBaseCapacity = 80,
    generationWeightByDepth = { { fromDepth = 4, weight = 18 } },
  },
  {
    id = "gold",
    name = "Gold",
    rarity = "rare",
    unlockDepth = 5,
    basePrice = 25,
    storageBaseCapacity = 60,
    generationWeightByDepth = { { fromDepth = 5, weight = 10 } },
  },
  {
    id = "platinum",
    name = "Platinum",
    rarity = "epic",
    unlockDepth = 6,
    basePrice = 40,
    storageBaseCapacity = 50,
    generationWeightByDepth = { { fromDepth = 6, weight = 6 } },
  },
  {
    id = "diamond",
    name = "Diamond",
    rarity = "epic",
    unlockDepth = 7,
    basePrice = 60,
    storageBaseCapacity = 40,
    generationWeightByDepth = { { fromDepth = 7, weight = 4 } },
  },
  {
    id = "mithril",
    name = "Mithril",
    rarity = "legendary",
    unlockDepth = 8,
    basePrice = 100,
    storageBaseCapacity = 30,
    generationWeightByDepth = { { fromDepth = 8, weight = 2 } },
  },
}

local byId = {}
for _, r in ipairs(resources) do
  byId[r.id] = r
end

return {
  list = resources,
  byId = byId,
}
